In [1]:
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
%matplotlib

Using matplotlib backend: Qt5Agg


In [2]:
class state:
    def __init__(self):
        self.r=np.array([0,0,1])
        self.u=np.array([0,0,1])
        self.t1=np.array([0,1,0])
        self.t2=np.array([1,0,0])
        
    def neuclosome(self,theta = 2*np.pi*0.67,
                   phi=2*np.pi*146*0.33/3.4 # 146bp  0.33nm/bp  pitch=3.4nm
                   ,h=2.0,rad=4.6):
        self.r = self.r - h*self.t1 # Helix offset 
        self.r = rotate(self.r,-self.t1,theta,self.r+rad*self.t2) # Winding r around
        self.u = rotate(self.u,-self.t1,theta,0.0) # Winding u around
        self.t2 = rotate(self.t2,-self.t1,theta,0.0) # Winding u around
        self.t1 = rotate(self.t1,self.u,phi,0.0) # natural twist
        self.t2 = rotate(self.t2,self.u,phi,0.0) # natural twist
        
    def get_neuclosome(self,h=2.0,rad=4.6):
        npts = 20
        vec = np.zeros((2*npts,3))
        for ii in range(0,npts):
            theta = 2*np.pi*ii/(npts-1)
            vec[ii,:]=rotate(self.r,-self.t1,theta,self.r+rad*self.t2)
            vec[ii+npts,:]=rotate(self.r,-self.t1,theta,self.r+rad*self.t2)-h*self.t1
        return vec
        
    def linker(self,L=0.33*50,pitch_in_nm=3.4):
        self.r = self.r + self.u*L
        phi = L*2*np.pi/pitch_in_nm
        self.t1 = rotate(self.t1,self.u,phi,0.0) # natural twist
        self.t2 = rotate(self.t2,self.u,phi,0.0) # natural twist        
    

In [3]:
def rotate(x,u,theta,offset=np.array([0,0,0])):
    
    x = x - offset
    
    R = axisAnge2matrix(u,theta)
    
    x =  np.dot(R,x)
    
    x = x + offset
    
    return x

def axisAnge2matrix(u,theta):
    u = u/np.linalg.norm(u)
    ux=u[0]
    uy=u[1]
    uz=u[2]
    uou = np.outer(u,u)
    u_x = np.array([[ 0, -uz,  uy],
                    [uz,   0, -ux],
                    [-uy, ux,  0 ]])
    I=np.identity(3)
    
    R = np.cos(theta)*I + np.sin(theta)*u_x + (1-np.cos(theta))*uou   
    return R

In [4]:
triad = state()
print(triad.r)
triad.neuclosome()
print(triad.r)
triad.linker()
print(triad.r)

[0 0 1]
[ 6.8160669  -2.          5.03101073]
[ 21.27512712  -2.          -2.91792489]


In [6]:
number_of_nucleosomes = 30
number_of_replicates = 1

data=np.array(np.zeros((number_of_nucleosomes*2,3,number_of_replicates)))
triad = state()

fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
for rep in range(0,number_of_replicates):
    for neu in range(0,number_of_nucleosomes):
        data[neu*2,:,rep]=triad.r
        
        L0=49
        Delta = 0
        L = L0+np.ceil((np.random.random(1)-0.5)*Delta)
        print(L)
        triad.linker(L=L*0.33)
        data[neu*2+1,:,rep]=triad.r
        
        xs=data[neu*2:neu*2+2,0,rep]
        ys=data[neu*2:neu*2+2,1,rep]
        zs=data[neu*2:neu*2+2,2,rep]
        ax.plot_wireframe(xs,ys,zs)
        
        vec = triad.get_neuclosome()
        xs = vec[:,0]
        ys = vec[:,1]
        zs = vec[:,2]
        ax.plot_wireframe(xs,ys,zs,color='r')
        
        plt.hold(True)
        
        triad.neuclosome()
plt.axis('equal')
plt.show()     


[ 49.]
[ 49.]
[ 49.]
[ 49.]
[ 49.]
[ 49.]
[ 49.]
[ 49.]
[ 49.]
[ 49.]
[ 49.]
[ 49.]
[ 49.]
[ 49.]
[ 49.]
[ 49.]
[ 49.]
[ 49.]
[ 49.]
[ 49.]
[ 49.]
[ 49.]
[ 49.]
[ 49.]
[ 49.]
[ 49.]
[ 49.]
[ 49.]
[ 49.]
[ 49.]
